version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:17"
      timezone: "Etc/UTC"

  - package-ecosystem: "nix"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:47"
      timezone: "Etc/UTC"
